menu:
    Blog: /
    # Archive: /archives/
    About: /About

favicon: /favicon.png
logo: /favicon.png

# Comment
# e.g disqus: seansun
disqus:
duoshuo:

# Analytics
google_analytics: UA-56015428-2

# Copyright Infomation
startyear: 2015
